### Técnicas de filtrado

In [4]:
import pandas as pd

weather = pd.read_csv('datos/weather_dataset.csv',
                        parse_dates = ['datetime'],
                        index_col = 'datetime')
weather.head()

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0

Suponer que se quieren los registros posteriores al 3 de Enero a las 6 pm y anteriores al 4 de Enero a las 11 am

In [9]:
inicio = pd.to_datetime('2009-01-03 16')
final = pd.to_datetime('2009-01-04 11')

#weather.loc[inicio:final]
weather.loc[(weather.index >= inicio) & (weather.index <= final)]

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-03 16:00:00,996.25,-2.80,270.65,-12.13,48.39,4.97,2.40,2.56,1.50,2.41,1282.51,1.82,2.50,240.6
2009-01-03 17:00:00,995.76,-4.69,268.80,-12.56,53.86,4.31,2.32,1.99,1.45,2.33,1290.94,2.63,3.50,248.8
2009-01-03 18:00:00,995.48,-4.08,269.43,-11.44,56.32,4.51,2.54,1.97,1.59,2.55,1287.53,3.12,4.63,250.5
2009-01-03 19:00:00,995.44,-3.78,269.73,-10.50,59.35,4.62,2.74,1.88,1.71,2.75,1285.95,0.96,2.13,236.3
2009-01-03 20:00:00,994.94,-3.84,269.72,-9.56,64.22,4.60,2.95,1.64,1.85,2.97,1285.48,0.91,2.13,143.4
2009-01-03 21:00:00,994.30,-3.15,270.45,-8.48,66.47,4.84,3.22,1.62,2.01,3.23,1281.27,0.97,2.00,220.0
2009-01-03 22:00:00,994.06,-2.76,270.86,-7.88,67.66,4.98,3.37,1.61,2.11,3.39,1279.04,1.03,2.00,214.8
2009-01-03 23:00:00,993.28,-2.58,271.10,-7.05,71.20,5.05,3.59,1.45,2.25,3.62,1277.07,1.60,4.25,237.7
2009-01-04 00:00:00,992.93,-1.90,271.81,-6.39,71.20,5.31,3.78,1.53,2.37,3.81,1273.31,1.47,2.50,147.6
2009-01-04 01:00:00,992.19,-1.42,272.35,-5.61,73.00,5.50,4.02,1.49,2.52,4.05,1270.01,2.77,4.75,232.1
2009-01-04 02:00:00,991.76,-2.22,271.58,-3.61,90.10,5.19,4.67,0.51,2.94,4.71,1272.89,1.82,4.75,201.9
2009-01-04 03:00:00,991.26,-2.20,271.64,-3.52,90.60,5.20,4.71,0.49,2.96,4.75,1272.12,0.87,1.88,94.4
2009-01-04 04:00:00,990.83,-1.88,272.00,-3.29,90.00,5.32,4.79,0.53,3.01,4.83,1270.02,0.62,1.75,167.3
2009-01-04 05:00:00,990.37,-1.64,272.28,-2.87,91.20,5.42,4.94,0.48,3.11,4.99,1268.23,1.31,3.13,215.4
2009-01-04 06:00:00,989.99,-1.44,272.50,-2.66,91.30,5.50,5.02,0.48,3.16,5.07,1266.78,1.00,2.38,200.9
2009-01-04 07:00:00,989.90,-1.09,272.86,-2.65,89.10,5.64,5.02,0.61,3.16,5.08,1265.04,2.75,5.75,246.8
2009-01-04 08:00:00,989.92,-0.89,273.06,-2.45,89.10,5.72,5.10,0.62,3.21,5.15,1264.12,2.93,5.00,242.6
2009-01-04 09:00:00,989.95,-0.72,273.23,-2.73,86.20,5.79,4.99,0.80,3.14,5.04,1263.42,1.70,3.88,254.0
2009-01-04 10:00:00,989.86,-1.37,272.59,-2.71,90.50,5.53,5.00,0.52,3.15,5.05,1266.28,2.59,4.50,232.9
2009-01-04 11:00:00,989.64,-1.10,272.87,-2.53,90.00,5.63,5.07,0.56,3.19,5.12,1264.75,2.38,4.50,234.6

Un intervalo de las primeras 8 horas del dia

In [11]:
inicio = pd.to_datetime('2009-01-01 00')

delta = pd.Timedelta(hours = 8)

final = inicio + delta

weather.loc[inicio:final]

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0
2009-01-01 06:00:00,997.71,-9.67,263.66,-10.62,92.7,2.93,2.71,0.21,1.69,2.72,1317.71,0.05,0.50,146.0
2009-01-01 07:00:00,998.33,-9.17,264.12,-10.10,92.9,3.04,2.83,0.22,1.76,2.83,1315.98,2.08,2.88,348.8
2009-01-01 08:00:00,999.17,-8.10,265.12,-9.05,92.8,3.31,3.07,0.24,1.92,3.08,1311.65,0.72,1.25,213.9

Cuando no interesan todas las columnas

In [23]:
inicio = pd.to_datetime('2009-01-01 00')

delta = pd.Timedelta(hours = 8)

final = inicio + delta

#weather.loc[(weather.index >= inicio) & (weather.index <= final), ['VPmax (mbar)', 'p (mbar)', 'Tdew (degC)']]
weather.loc[inicio:final, ['VPmax (mbar)', 'p (mbar)', 'Tdew (degC)']]

                     VPmax (mbar)  p (mbar)  Tdew (degC)
datetime
2009-01-01 01:00:00          3.33    996.50        -8.78
2009-01-01 02:00:00          3.12    996.62        -9.77
2009-01-01 03:00:00          3.13    996.84        -9.66
2009-01-01 04:00:00          3.07    996.99       -10.02
2009-01-01 05:00:00          2.94    997.46       -10.65
2009-01-01 06:00:00          2.93    997.71       -10.62
2009-01-01 07:00:00          3.04    998.33       -10.10
2009-01-01 08:00:00          3.31    999.17        -9.05

Usando metodos del DataFrame

In [24]:
weather.at_time('5')

/tmp/ipykernel_46831/862680550.py:1: Pandas4Warning: The string '5' cannot be parsed using pd.core.tools.to_time and in a future version will raise. Use an unambiguous time string format or explicitly cast to `datetime.time` before calling.
  weather.at_time('5')

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-02,999.59,-4.54,268.65,-5.46,93.2,4.36,4.06,0.30,2.53,4.06,1294.33,0.41,0.88,155.00
2009-01-03,1002.32,-4.71,268.27,-6.09,90.0,4.30,3.87,0.43,2.41,3.86,1298.79,1.42,1.88,16.85
2009-01-04,992.93,-1.90,271.81,-6.39,71.2,5.31,3.78,1.53,2.37,3.81,1273.31,1.47,2.50,147.60
2009-01-05,985.07,-1.47,272.86,-2.45,93.0,5.48,5.10,0.38,3.23,5.18,1260.58,1.42,3.00,239.80
2009-01-06,997.60,-12.63,260.71,-15.07,81.8,2.31,1.89,0.42,1.18,1.89,1332.96,1.60,2.63,355.50
2009-01-07,994.51,-21.09,252.47,-23.01,84.3,1.13,0.95,0.18,0.59,0.95,1373.91,0.48,1.00,168.40
2009-01-08,998.53,-10.78,262.49,-11.88,91.5,2.68,2.45,0.23,1.53,2.45,1324.52,0.37,0.75,196.20
2009-01-09,1003.66,-13.91,258.98,-15.06,90.9,2.08,1.89,0.19,1.17,1.88,1347.69,1.00,1.50,217.90
2009-01-10,1003.63,-13.24,259.65,-14.57,89.6,2.19,1.97,0.23,1.22,1.96,1344.13,0.49,1.00,172.10
2009-01-11,1002.72,-10.75,262.21,-11.76,92.2,2.69,2.48,0.21,1.54,2.47,1329.91,0.74,1.88,109.70
2009-01-12,1003.34,-8.96,263.95,-10.57,88.0,3.10,2.72,0.37,1.69,2.72,1321.60,2.71,4.38,174.00
2009-01-13,993.54,-5.19,268.47,-10.44,66.4,4.15,2.75,1.39,1.73,2.77,1290.26,2.20,3.25,172.50
2009-01-14,988.02,-4.41,269.68,-8.30,74.1,4.40,3.26,1.14,2.06,3.30,1279.11,1.83,2.75,212.50
2009-01-15,990.20,0.44,274.37,-0.90,90.7,6.30,5.72,0.59,3.60,5.78,1258.04,1.58,3.25,221.10
2009-01-16,997.57,-4.03,269.32,-4.33,97.7,4.53,4.43,0.10,2.76,4.44,1289.06,1.58,2.00,145.50
2009-01-17,995.14,-2.30,271.23,-3.95,88.4,5.15,4.56,0.60,2.85,4.58,1277.68,2.75,4.00,187.00
2009-01-18,987.96,1.94,276.05,-0.10,86.3,7.03,6.06,0.96,3.83,6.14,1248.16,1.57,2.13,194.80
2009-01-19,978.22,2.89,277.79,-1.18,74.5,7.52,5.60,1.92,3.57,5.73,1231.80,3.58,6.00,230.30
2009-01-20,966.01,4.08,280.00,2.33,88.3,8.19,7.23,0.96,4.67,7.48,1210.37,1.24,2.50,28.72
2009-01-21,977.43,-2.96,271.97,-3.61,95.3,4.91,4.68,0.23,2.98,4.78,1257.91,1.27,2.25,177.90
2009-01-22,983.51,-3.62,270.82,-4.05,96.8,4.67,4.52,0.15,2.86,4.60,1268.92,0.54,1.25,149.20
2009-01-23,971.40,-0.75,274.68,-3.63,80.7,5.78,4.67,1.12,2.99,4.80,1239.97,5.69,7.50,171.80
2009-01-24,952.33,3.93,280.99,-0.71,71.6,8.10,5.80,2.30,3.80,6.09,1194.52,7.41,11.00,212.50
2009-01-25,971.14,0.29,275.75,-1.92,85.0,6.24,5.30,0.94,3.40,5.46,1234.61,0.71,2.13,110.50
2009-01-26,975.21,-3.28,271.83,-3.89,95.5,4.79,4.58,0.22,2.92,4.69,1256.56,1.28,2.00,210.90
2009-01-27,980.97,-1.14,273.52,-1.79,95.3,5.62,5.35,0.26,3.40,5.46,1253.67,0.50,1.25,18.44
2009-01-28,990.97,-1.68,272.19,-1.68,100.0,5.40,5.40,0.00,3.40,5.45,1268.98,0.00,0.00,0.00
2009-01-29,995.05,-2.74,270.80,-4.29,89.0,4.99,4.44,0.55,2.78,4.46,1279.68,0.00,0.00,0.00
2009-01-30,998.82,-1.96,271.29,-4.50,82.7,5.29,4.37,0.91,2.73,4.38,1280.90,1.55,3.50,76.20
2009-01-31,997.42,-2.48,270.88,-4.05,88.9,5.09,4.52,0.56,2.82,4.53,1281.48,2.11,2.63,29.18
2009-02-01,989.86,-2.97,270.98,-5.04,85.5,4.91,4.19,0.71,2.64,4.24,1274.18,4.57,6.50,32.40
2009-02-02,982.74,-2.54,271.97,-4.33,87.4,5.07,4.43,0.64,2.81,4.51,1262.88,3.43,5.13,38.57
2009-02-03,976.35,-0.90,274.13,-2.11,91.4,5.72,5.23,0.49,3.34,5.35,1246.71,0.10,0.63,101.40
2009-02-04,972.68,-2.64,272.67,-3.06,96.9,5.03,4.87,0.16,3.12,5.01,1250.20,0.11,0.50,137.60
2009-02-05,972.48,0.78,276.14,0.19,95.8,6.47,6.19,0.27,3.97,6.37,1233.68,1.32,2.00,188.50
2009-02-06,971.67,0.78,276.20,-1.10,87.2,6.46,5.64,0.83,3.62,5.80,1232.94,1.89,2.75,190.20
2009-02-07,963.93,0.82,276.87,-1.79,82.6,6.48,5.35,1.13,3.46,5.55,1223.06,1.27,1.88,220.30
2009-02-08,965.76,2.21,278.12,0.64,89.3,7.16,6.40,0.77,4.13,6.62,1218.71,1.98,3.75,255.40
2009-02-09,980.43,-2.34,272.35,-5.42,79.3,5.14,4.08,1.06,2.59,4.16,1259.17,1.45,2.25,190.40
2009-02-10,973.46,-0.13,275.14,-3.57,77.5,6.05,4.69,1.36,3.00,4.82,1239.77,2.91,3.75,193.40
2009-02-11,969.30,0.67,276.28,-2.48,79.3,6.41,5.09,1.33,3.27,5.25,1230.67,3.00,5.63,263.10
2009-02-12,983.22,-0.27,274.22,-2.34,85.8,5.99,5.14,0.85,3.26,5.23,1252.64,2.14,3.63,246.00
2009-02-13,989.26,-2.13,271.87,-4.57,83.3,5.22,4.35,0.87,2.74,4.40,1269.42,2.37,3.88,256.90
2009-02-14,989.00,-0.69,273.33,-1.52,94.1,5.81,5.46,0.34,3.44,5.52,1261.84,0.85,1.75,233.30
2009-02-15,1000.46,-5.27,267.85,-7.33,85.3,4.12,3.52,0.61,2.19,3.51,1299.27,1.90,2.50,263.70
2009-02-16,993.86,-2.94,270.70,-4.21,90.9,4.92,4.47,0.45,2.80,4.50,1279.09,2.74,4.75,165.40
2009-02-17,987.40,-0.23,273.92,-0.78,96.0,6.01,5.77,0.24,3.64,5.84,1257.50,2.02,2.75,147.70
2009-02-18,999.12,-4.97,268.26,-6.58,88.4,4.22,3.73,0.49,2.32,3.73,1295.94,1.69,3.63,3.64
2009-02-19,998.58,-7.90,265.37,-9.38,89.0,3.36,2.99,0.37,1.87,3.00,1309.93,1.24,1.75,219.20
2009-02-20,997.01,-2.44,270.95,-4.02,88.8,5.10,4.53,0.57,2.83,4.55,1280.73,1.76,3.00,196.90
2009-02-21,998.81,1.53,274.78,1.05,96.6,6.82,6.59,0.23,4.11,6.60,1263.54,2.01,3.13,238.60

In [25]:
weather.at_time('5')['VPmax (mbar)']

/tmp/ipykernel_46831/861510205.py:1: Pandas4Warning: The string '5' cannot be parsed using pd.core.tools.to_time and in a future version will raise. Use an unambiguous time string format or explicitly cast to `datetime.time` before calling.
  weather.at_time('5')['VPmax (mbar)']

datetime
2009-01-02    4.36
2009-01-03    4.30
2009-01-04    5.31
2009-01-05    5.48
2009-01-06    2.31
2009-01-07    1.13
2009-01-08    2.68
2009-01-09    2.08
2009-01-10    2.19
2009-01-11    2.69
2009-01-12    3.10
2009-01-13    4.15
2009-01-14    4.40
2009-01-15    6.30
2009-01-16    4.53
2009-01-17    5.15
2009-01-18    7.03
2009-01-19    7.52
2009-01-20    8.19
2009-01-21    4.91
2009-01-22    4.67
2009-01-23    5.78
2009-01-24    8.10
2009-01-25    6.24
2009-01-26    4.79
2009-01-27    5.62
2009-01-28    5.40
2009-01-29    4.99
2009-01-30    5.29
2009-01-31    5.09
2009-02-01    4.91
2009-02-02    5.07
2009-02-03    5.72
2009-02-04    5.03
2009-02-05    6.47
2009-02-06    6.46
2009-02-07    6.48
2009-02-08    7.16
2009-02-09    5.14
2009-02-10    6.05
2009-02-11    6.41
2009-02-12    5.99
2009-02-13    5.22
2009-02-14    5.81
2009-02-15    4.12
2009-02-16    4.92
2009-02-17    6.01
2009-02-18    4.22
2009-02-19    3.36
2009-02-20    5.10
2009-02-21    6.82
Name: VPmax (mbar), dtype: float64

In [28]:
weather.between_time('5:00', '10:00')['VPmax (mbar)']

datetime
2009-01-01 05:00:00    2.94
2009-01-01 06:00:00    2.93
2009-01-01 07:00:00    3.04
2009-01-01 08:00:00    3.31
2009-01-01 09:00:00    3.43
                       ...
2009-02-21 06:00:00    6.30
2009-02-21 07:00:00    6.24
2009-02-21 08:00:00    6.20
2009-02-21 09:00:00    6.18
2009-02-21 10:00:00    6.33
Name: VPmax (mbar), Length: 312, dtype: float64

### Ejercicio práctico

Determinar los días/horas para las cuales la temperatura sobrepasó el promedio +2 desviaciónes estándar tomando como referencia los primeros 15 días de Enero usando formato 'Monday 12, 15:00'

In [86]:
weather = pd.read_csv('datos/weather_dataset.csv',
                        parse_dates = ['datetime'],
                        index_col = 'datetime')
weather.head()

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
datetime,,,,,,,,,,,,,,
2009-01-01 01:00:00,996.50,-8.05,265.38,-8.78,94.4,3.33,3.14,0.19,1.96,3.15,1307.86,0.21,0.63,192.7
2009-01-01 02:00:00,996.62,-8.88,264.54,-9.77,93.2,3.12,2.90,0.21,1.81,2.91,1312.25,0.25,0.63,190.3
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.5,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 04:00:00,996.99,-9.05,264.34,-10.02,92.6,3.07,2.85,0.23,1.78,2.85,1313.61,0.10,0.38,240.0
2009-01-01 05:00:00,997.46,-9.63,263.72,-10.65,92.2,2.94,2.71,0.23,1.69,2.71,1317.19,0.40,0.88,157.0

In [92]:
inicio = pd.to_datetime('2009-01-01 00')
delta = pd.Timedelta(days = 15)
final = inicio + delta

temps = weather.loc[:'2009-01-15', 'T (degC)']
temp_umbral = temps.mean() +  2*temps.std()
print(f'T umbral: {temp_umbral}')
temps[temps >= temp_umbral]

T umbral: 4.462821614005941

datetime
2009-01-13 14:00:00    4.63
2009-01-13 15:00:00    4.89
2009-01-15 15:00:00    4.52
Name: T (degC), dtype: float64

In [97]:
fechas_horas = temps[temps >= temp_umbral].index
for item in fechas_horas:
    print(item.strftime('%A %d, %H:%M'))

Tuesday 13, 14:00
Tuesday 13, 15:00
Thursday 15, 15:00